### ISSUE TITLE
training details

### ISSUE THREAD

**Issue by AdamAsh2019** [ElliotHYLee/Deep_Visual_Inertial_Odometry#1]
Hi, thanks for releasing your code, such a wonderful work. I want to use your code to train kitti dataset, however i could not find the kitti data interface in your code.

**Comment by ElliotHYLee** [comment]
Thanks for your interest. Indeed, that part is a mess at the moment. The relevant codes are in DataUtils.py, ReadData.py, PrepData.py.

DataUtils has all path-wise information.
ReadData just reads all based on the paths in DataUtils
PrepData manufactures the data for train and test.
