### ISSUE TITLE
where imu data ?

### ISSUE THREAD

**Issue by fangxu622** [ElliotHYLee/Deep_Visual_Inertial_Odometry#2]

**Comment by fangxu622** [comment]
Does the imu data from fake acc signal?

**Comment by ElliotHYLee** [comment]
Hi @fangxu622 
Short answer: it depends on the dataset
long answer: The master version only considers KITTI at the moment. As you know KITTI does not have real IMU data. Using ground truth and log map, rotation and position given two frames at t and t+1 are calculated. The differential rotation + gaussian noise is regarded as gyroscope signal. The linear acceleration is calculated using frame2frame movement / dt. 

For AirSim, the inertial information is provided. 

-------------------------

I will try to upload some sample data sooner or later.
