### ISSUE TITLE
'image_2' Not a folder in the KITTI Dataset

### ISSUE THREAD

**Issue by houstoncamden** [ElliotHYLee/Deep_Visual_Inertial_Odometry#4]
Hi, I'm trying to get this library to run on a windows 10 machine, and after specifying the correct directory for the image data, I'm still getting an error that the code wants a folder of images 'image_2'. As far as I can tell, this folder isn't available in any of the existing KITTI Datasets, and changing the folder to 'image_0', or 'image_1', which do exist, results in an error related to an empty tensor. Any advice or insight would be greatly appreciated.

**Comment by ElliotHYLee** [comment]
Image 0 and 1 are left & right grey scales and 2 and3 are RGB images. This project is based on the left RGB images. Please download the rgb images from the KITTI web.

**Comment by houstoncamden** [comment]
Thank you!
