### ISSUE TITLE
Empty Tensor

### ISSUE THREAD

**Issue by houstoncamden** [ElliotHYLee/Deep_Visual_Inertial_Odometry#5]
Thanks so much for your earlier help. However, I'm having another issue with the code. I get the following error:
0    000000.png       
Name: 0, dtype: object
1
# of thread reading imgs: 1
0    000000.png       
Name: 0, dtype: object
1
# of thread reading imgs: 1
0    000000.png       
Name: 0, dtype: object
1
# of thread reading imgs: 1
0    000000.png       
Name: 0, dtype: object
1
# of thread reading imgs: 1
[4540, 4660, 270, 1100]
10570
numeric data concat
done numeric data concat     
img data concat
done img data concat
preparing to standardize imgs
standardizing imgs
done standardizing imgs
standardizing gyro
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
0 10246
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
1 9046
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
2 5065
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
3 6863
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
4 3924
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
5 10194
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
6 6076
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
7 3942
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
8 4238
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
9 2683
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
10 2667
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
11 2433
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
12 8765
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
13 379
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
14 1800
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
15 579
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
16 3224
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
17 6704
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
18 7791
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
19 4593
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
20 1880
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
21 3362
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
22 8462
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
23 10348
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
24 2456
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
25 7999
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
26 7461
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
27 7104
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
28 659
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
29 6248
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
30 2797
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
31 2893
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
32 7373
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
33 3624
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
34 6634
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
35 7015
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
36 6065
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
37 7749
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
38 6880
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
39 6008
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
40 5303
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
41 6302
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
42 6939
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
43 4620
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
44 8382
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
45 61
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
46 5599
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
47 7545
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
48 4589
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
49 9876
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
50 6481
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
51 8242
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
52 1302
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
53 2422
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
54 65
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
55 3004
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
56 9716
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
57 5569
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
58 834
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
59 4147
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
60 9984
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
61 1736
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
62 5975
this is an error @ VODataSet_CNN of VODataSet.py
(4, 3, 360, 720)
63 694
Traceback (most recent call last):
  File "f:\OSU VIO\Deep_Visual_Intertial_Odometry\main_cnn.py", line 56, in <module>
    runTrainTest('kitti', 'none', seq=[0, 2, 4, 6], seqRange=[0, 11])
  File "f:\OSU VIO\Deep_Visual_Intertial_Odometry\main_cnn.py", line 40, in runTrainTest
    runTrain(dsName, subType, seq)
  File "f:\OSU VIO\Deep_Visual_Intertial_Odometry\main_cnn.py", line 45, in runTrain
    train(dsName, subType, seq)
  File "f:\OSU VIO\Deep_Visual_Intertial_Odometry\main_cnn.py", line 12, in train
    mc.regress(dm, epochs=20, batch_size=64, shuffle=False)
  File "f:\OSU VIO\Deep_Visual_Intertial_Odometry\MyPyTorchAPI\AbsModelContainer.py", line 80, in regress
    self.forward(epochs=epochs, dataLoader=self.trainLoader, forwardCase=0)
  File "f:\OSU VIO\Deep_Visual_Intertial_Odometry\MyPyTorchAPI\AbsModelContainer.py", line 95, in forward
    for batch_idx, dataInTuple in enumerate(dataLoader):
  File "C:\Users\owner\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\owner\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\owner\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\_utils\collate.py", line 86, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>

I suspect that this may be because I've generated my own "fNames.txt' file, and the CSV reader is having issues parsing it out. Could you share the format of your fNames.txt file so that I can match that in my own? Or do you think this might be caused by some separate issue that I'm not aware of?

**Comment by ElliotHYLee** [comment]
The file should simply contain:
000000.png
000001.png
....
and so on

**Comment by houstoncamden** [comment]
This was the issue! Thank you so much
